name: Daily Re:Zero Scraper

on:
  schedule:
    - cron: '50 20 * * *'   # JST 5:50
    - cron: '50 2 * * *'    # JST 11:50
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python scrape.py

    - name: Commit and push
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git add latest.txt
      git commit -m "Update latest title" || exit 0
      git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main


